# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:3001/api/register
Content-Type: application/json

{
  "username": "client1",
  "password": "client",
  "dummyval": "123qwe"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST http://screenz.shprota.com/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST http://localhost:3001/api/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

###

POST http://localhost:3001/api/token
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

GET http://localhost:3001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNTg5MThhZmYyY2Y4Njk3NmI2MDU2MSIsImlhdCI6MTU0OTMwODI5OCwiZXhwIjoxNTU1MzA4Mjk4fQ.2-N3q3b6OmfCBAN1SqXrcItVOPBI5i4uY5gvq7JQRgU

###

GET http://localhost:3001/api/renew_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNTg4NGI3MGFkMTRjNWUyMmUxNDgzNiIsImlhdCI6MTU0OTMwNTAyMSwiZXhwIjoxNTU1MzA1MDIxfQ.4H5GUc6Z4go-k13h7NqOZ2PJ0wwbF6oTcxecA9CsNS0

###

GET http://localhost:3001/api/renew_token
Cookie: connect.sid=s%3AKJRf_vC77iLSu3F6EmczkoPnAsnLfTtN.qvPNf96aNkXrnMqHmM2DN9i%2Bn7pwcI3c8x2KwcLzbwM; Path=/;

###

POST http://localhost:3001/api/genres
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNThjYzEyOGQ1YTQ2NDMyMGQ4NDE1YyIsImlhdCI6MTU0OTMyMzYxMiwiZXhwIjoxNTU1MzIzNjEyfQ.NcD51sApIoiLoERtVo83GkAzRZ204WquaOtxuXJQXuo

{
  "name": "Fiction"
}

###

GET http://localhost:3001/api/genres

###
DELETE http://localhost:3001/api/genres/5c589119e82ff368c764676b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNTg5MThhZmYyY2Y4Njk3NmI2MDU2MSIsImlhdCI6MTU0OTMwODY3NiwiZXhwIjoxNTU1MzA4Njc2fQ.sObb-MUY5dxsuASqg37eHDcS5lmGD83C0xwWMJ7Ap94

###

POST http://localhost:3001/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNThjYzEyOGQ1YTQ2NDMyMGQ4NDE1YyIsImlhdCI6MTU0OTMyMzYxMiwiZXhwIjoxNTU1MzIzNjEyfQ.NcD51sApIoiLoERtVo83GkAzRZ204WquaOtxuXJQXuo

{
  "name": "Everything I Know about Women I Learned from My Tractor",
  "genre": "5c58cda588091d4d24329e92",
  "description": "Best-selling author and humorist Roger Welsch comes through again as he delivers his outrageous anecdotes from the farm fields of Nebraska. Jam-packed with Rog's creative techniques for picking up babes, buying suitable gifts for anniversaries, first dates and more! Roger digs deep into his own down-home experiences to deliver his comic and witty take on love, sex, romance, and marriage as he guides more innocent generations down the same road to success that he enjoys in his own relationships. This humorous guide examines everything from evading capture and the old catch-and-release tactic, to the dreaded blind date. This \"ultimate contribution to mankind\" reveals the coveted trade secrets Roger Welsch holds dear and deserves prominent placement on the bookshelf of every self-respecting male."
}

###

GET http://localhost:3001/api/books

###

POST http://localhost:3001/api/books/review/5c58d1ba59ab5853d840683f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNThjYzEyOGQ1YTQ2NDMyMGQ4NDE1YyIsImlhdCI6MTU0OTMyMzYxMiwiZXhwIjoxNTU1MzIzNjEyfQ.NcD51sApIoiLoERtVo83GkAzRZ204WquaOtxuXJQXuo

{
  "rating": 9,
  "description": "I really loughed at some of the jokes"
}

###

POST http://localhost:3001/api/books/review/5c58d1ba59ab5853d840683f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjNThjYzEyOGQ1YTQ2NDMyMGQ4NDE1YyIsImlhdCI6MTU0OTMyMzYxMiwiZXhwIjoxNTU1MzIzNjEyfQ.NcD51sApIoiLoERtVo83GkAzRZ204WquaOtxuXJQXuo

{
  "rating": 9,
  "description": "I really loughed the fucking shit our of me"
}

###